meta:
    site_title: "shousunny的博客"
    site_subtitle: "人生就是不停的战斗"
    site_language: "zh-cn"
    absolute_baseurl: https://shousunny.github.io/
    domain: shousunny.github.io
    author:
        full_name: Shou Sunny
        short_name: SS
        name: sunny
        email: shousunny@foxmail.com

url: https://shousunny.github.io/

baseurl: /

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: SSstory

      
css:
    - css/screen.css


